// @ts-ignore
import { useContext, WithChildrenProps } from "react";

import Header from './Header';
import { SettingsContext } from '../components/SettingsContext';

import AppStyles from '../styles/App.module.scss';
import Footer from '../components/Footer';
import Head from "next/head";
import { Poppins } from '@next/font/google';

const poppins = Poppins({
    weight: ['400', '500'],
    subsets: ['latin']
});

export default function Base({ children }: WithChildrenProps ) {
    const { settings } = useContext(SettingsContext);

    return (
        <>
        <Head>
            <title>Dan's Portfolio Site</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`App ${poppins.className}`} data-theme={settings.theme + "-" + settings.scheme}>
            <Header />
            <div className={AppStyles.content}>
                {children}
            </div>
            <Footer />
        </div>
        </>
    )
}
